# -*- coding: utf-8 -*-
"""prodigytask1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/Sasi-2002-max/c878196b8407e66f147bb73afcf24f8b/prodigytask1.ipynb
"""

# Step 1: Import necessary libraries
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Step 2: Load a sample dataset (Titanic dataset)
df = sns.load_dataset('titanic')

# Step 3: Drop missing age values (for histogram)
df_age = df.dropna(subset=['age'])

# Step 4: Create a bar chart for gender distribution
plt.figure(figsize=(6, 4))
sns.countplot(x='sex', data=df)
plt.title('Gender Distribution')
plt.xlabel('Gender')
plt.ylabel('Count')
plt.show()

# Step 5: Create a histogram for age distribution
plt.figure(figsize=(8, 5))
sns.histplot(df_age['age'], bins=20, kde=True, color='skyblue')
plt.title('Age Distribution')
plt.xlabel('Age')
plt.ylabel('Frequency')
plt.show()